version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: leadbox
      POSTGRES_PASSWORD: leadbox
      POSTGRES_DB: leadbox
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: redis-server --save '' --appendonly no
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  minio:
    image: minio/minio:RELEASE.2024-02-17T01-15-57Z
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: leadbox
      MINIO_ROOT_PASSWORD: leadboxpass
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
volumes:
  postgres-data:
  redis-data:
  minio-data:
